Repository rubberdok/indok-web, pull requests merged in 2022-01, with the labels that each got.

#328 🤖 ci(dependabot, dok-201): re-add dependabot config
  .github/dependabot.yml
Labels: dependencies

#327 📈 tracing(dok-253): capture, send exceptions to sentry frontend
  frontend/next.config.js
  frontend/src/pages/_app.tsx
  frontend/src/pages/_error.tsx
Labels: enhancement, javascript

#417 feat: graduation year validation, always show users' graduation year
  frontend/src/components/pages/profile/UserForm/helpers.ts
  frontend/src/components/pages/profile/UserForm/index.tsx
Labels: enhancement

#411 Add a number of improvements to Vipps pages
  backend/apps/ecommerce/mutations.py
  backend/apps/ecommerce/tests.py
  backend/apps/ecommerce/vipps_utils.py
  frontend/src/components/pages/ecommerce/OrderCellContent.tsx
  frontend/src/components/pages/ecommerce/PayWithVipps.tsx
  frontend/src/components/pages/ecommerce/SalesTermsDialog.tsx
  frontend/src/components/pages/events/EventDetails.tsx
  frontend/src/components/pages/events/org/OrgEventsTable.tsx
  frontend/src/graphql/ecommerce/mutations.ts
  frontend/src/interfaces/utils.ts
  frontend/src/pages/ecommerce/checkout.tsx
  frontend/src/pages/ecommerce/fallback.tsx
  frontend/src/pages/ecommerce/index.tsx
  frontend/src/pages/orgs/[orgId]/events/[eventId].tsx
Labels: enhancement
